//
//  TITLE:    SignalFileErrStr.h
//  AUTHOR:   Greg Rishea
//  DATE:     2000.08.17
//  SUMMARY:  SignaFile error string constant definitions.
//
//  UPDATES:  
//

#ifndef __SIGNALFILEERRSTR_H_
#define __SIGNALFILEERRSTR_H_

#define IDS_SIGNALFILE_ERROR_BASE                1000

#define IDS_SIGNALFILE_ERROR_FAIL                1000
#define IDS_SIGNALFILE_ERROR_FILENOTOPEN         1001
#define IDS_SIGNALFILE_ERROR_FILEALREADYOPEN     1002
#define IDS_SIGNALFILE_ERROR_FILEDOESNTEXIST     1003
#define IDS_SIGNALFILE_ERROR_FILEALREADYEXISTS   1004
#define IDS_SIGNALFILE_ERROR_FILEINVALID         1005
#define IDS_SIGNALFILE_ERROR_FILEACCESSFAIL      1006
#define IDS_SIGNALFILE_ERROR_FILECREATEFAIL      1007
#define IDS_SIGNALFILE_ERROR_FILEOPENFAIL        1008
#define IDS_SIGNALFILE_ERROR_FILECLOSEFAIL       1009
#define IDS_SIGNALFILE_ERROR_FILEPOSITIONFAIL    1010
#define IDS_SIGNALFILE_ERROR_FILEREADFAIL        1011
#define IDS_SIGNALFILE_ERROR_FILEWRITEFAIL       1012
#define IDS_SIGNALFILE_ERROR_FILEFLUSHFAIL       1013
#define IDS_SIGNALFILE_ERROR_FILECOPYFAIL        1014
#define IDS_SIGNALFILE_ERROR_FILERENAMEFAIL      1015
#define IDS_SIGNALFILE_ERROR_FILEDELETEFAIL      1016
#define IDS_SIGNALFILE_ERROR_OBJECTINVALID       1017
#define IDS_SIGNALFILE_ERROR_OBJECTREADONLY      1018
#define IDS_SIGNALFILE_ERROR_OBJECTCHANGEFAIL    1019
#define IDS_SIGNALFILE_ERROR_SUBOBJECTCREATEFAIL 1020
#define IDS_SIGNALFILE_ERROR_SUBOBJECTINITFAIL   1021
#define IDS_SIGNALFILE_ERROR_SUBOBJECTRESETFAIL  1022
#define IDS_SIGNALFILE_ERROR_SUBOBJECTINVALID    1023

#endif // !__SIGNALFILEERRSTR_H_
